<?php

if(function_exists("register_field_group"))
{
    register_field_group(array (
        'id' => 'acf_event-information',
        'title' => 'Event Information',
        'fields' => array (
            array (
                'key' => 'field_595ee9719b34a',
                'label' => 'Date',
                'name' => 'date',
                'type' => 'date_picker',
                'date_format' => 'yymmdd',
                'display_format' => 'dd/mm/yy',
                'first_day' => 1,
            ),
            array (
                'key' => 'field_595ee99a9b34b',
                'label' => 'Start time',
                'name' => 'start_time',
                'type' => 'select',
                'choices' => array (
                    999999 => 'No Start Time',
                    600 => '6:00am',
                    615 => '6:15am',
                    630 => '6:30am',
                    645 => '6:45am',
                    700 => '7:00am',
                    715 => '7:15am',
                    730 => '7:30am',
                    745 => '7:45am',
                    800 => '8:00am',
                    815 => '8:15am',
                    830 => '8:30am',
                    845 => '8:45am',
                    900 => '9:00am',
                    915 => '9:15am',
                    930 => '9:30am',
                    945 => '9:45am',
                    1000 => '10:00am',
                    1015 => '10:15am',
                    1030 => '10:30am',
                    1045 => '10:45am',
                    1100 => '11:00am',
                    1115 => '11:15am',
                    1130 => '11:30am',
                    1145 => '11:45am',
                    1200 => '12:00pm',
                    1215 => '12:15pm',
                    1230 => '12:30pm',
                    1245 => '12:45pm',
                    1300 => '1:00pm',
                    1315 => '1:15pm',
                    1330 => '1:30pm',
                    1345 => '1:45pm',
                    1400 => '2:00pm',
                    1415 => '2:15pm',
                    1430 => '2:30pm',
                    1445 => '2:45pm',
                    1500 => '3:00pm',
                    1515 => '3:15pm',
                    1530 => '3:30pm',
                    1545 => '3:45pm',
                    1600 => '4:00pm',
                    1615 => '4:15pm',
                    1630 => '4:30pm',
                    1645 => '4:45pm',
                    1700 => '5:00pm',
                    1715 => '5:15pm',
                    1730 => '5:30pm',
                    1745 => '5:45pm',
                    1800 => '6:00pm',
                    1815 => '6:15pm',
                    1830 => '6:30pm',
                    1845 => '6:45pm',
                    1900 => '7:00pm',
                    1915 => '7:15pm',
                    1930 => '7:30pm',
                    1945 => '7:45pm',
                    2000 => '8:00pm',
                    2015 => '8:15pm',
                    2030 => '8:30pm',
                    2045 => '8:45pm',
                    2100 => '9:00pm',
                    2115 => '9:15pm',
                    2130 => '9:30pm',
                    2145 => '9:45pm',
                    2200 => '10:00pm',
                    2215 => '10:15pm',
                    2230 => '10:30pm',
                    2245 => '10:45pm',
                    2300 => '11:00pm',
                    2315 => '11:15pm',
                    2330 => '11:30pm',
                    2345 => '11:45pm',
                ),
                'default_value' => '',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_595eea6c9b34c',
                'label' => 'End time',
                'name' => 'end_time',
                'type' => 'select',
                'choices' => array (
                    999999 => 'No End Time',
                    600 => '6:00am',
                    615 => '6:15am',
                    630 => '6:30am',
                    645 => '6:45am',
                    700 => '7:00am',
                    715 => '7:15am',
                    730 => '7:30am',
                    745 => '7:45am',
                    800 => '8:00am',
                    815 => '8:15am',
                    830 => '8:30am',
                    845 => '8:45am',
                    900 => '9:00am',
                    915 => '9:15am',
                    930 => '9:30am',
                    945 => '9:45am',
                    1000 => '10:00am',
                    1015 => '10:15am',
                    1030 => '10:30am',
                    1045 => '10:45am',
                    1100 => '11:00am',
                    1115 => '11:15am',
                    1130 => '11:30am',
                    1145 => '11:45am',
                    1200 => '12:00pm',
                    1215 => '12:15pm',
                    1230 => '12:30pm',
                    1245 => '12:45pm',
                    1300 => '1:00pm',
                    1315 => '1:15pm',
                    1330 => '1:30pm',
                    1345 => '1:45pm',
                    1400 => '2:00pm',
                    1415 => '2:15pm',
                    1430 => '2:30pm',
                    1445 => '2:45pm',
                    1500 => '3:00pm',
                    1515 => '3:15pm',
                    1530 => '3:30pm',
                    1545 => '3:45pm',
                    1600 => '4:00pm',
                    1615 => '4:15pm',
                    1630 => '4:30pm',
                    1645 => '4:45pm',
                    1700 => '5:00pm',
                    1715 => '5:15pm',
                    1730 => '5:30pm',
                    1745 => '5:45pm',
                    1800 => '6:00pm',
                    1815 => '6:15pm',
                    1830 => '6:30pm',
                    1845 => '6:45pm',
                    1900 => '7:00pm',
                    1915 => '7:15pm',
                    1930 => '7:30pm',
                    1945 => '7:45pm',
                    2000 => '8:00pm',
                    2015 => '8:15pm',
                    2030 => '8:30pm',
                    2045 => '8:45pm',
                    2100 => '9:00pm',
                    2115 => '9:15pm',
                    2130 => '9:30pm',
                    2145 => '9:45pm',
                    2200 => '10:00pm',
                    2215 => '10:15pm',
                    2230 => '10:30pm',
                    2245 => '10:45pm',
                    2300 => '11:00pm',
                    2315 => '11:15pm',
                    2330 => '11:30pm',
                    2345 => '11:45pm',
                ),
                'default_value' => '',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_595eeb6f9b351',
                'label' => 'Free event',
                'name' => 'free_event',
                'type' => 'true_false',
                'message' => 'This is a free event',
                'default_value' => 0,
            ),
            array (
                'key' => 'field_595eeb909b352',
                'label' => 'Cost',
                'name' => 'cost',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_595eeb6f9b351',
                            'operator' => '!=',
                            'value' => '1',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '$',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_595ee8fd9b345',
                'label' => 'Short description',
                'name' => 'short_description',
                'type' => 'text',
                'instructions' => '(25 words)',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_595ee9179b346',
                'label' => 'Long description',
                'name' => 'long_description',
                'type' => 'textarea',
                'instructions' => '(150 words)',
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'formatting' => 'br',
            ),
            array (
                'key' => 'field_595eeb9c9b353',
                'label' => 'Partners',
                'name' => 'partners',
                'type' => 'wysiwyg',
                'default_value' => '',
                'toolbar' => 'full',
                'media_upload' => 'yes',
            ),
            array (
                'key' => 'field_595eebbb9b354',
                'label' => 'Sponsors',
                'name' => 'sponsors',
                'type' => 'wysiwyg',
                'default_value' => '',
                'toolbar' => 'full',
                'media_upload' => 'yes',
            ),
            array (
                'key' => 'field_595ee9489b348',
                'label' => 'Event logo',
                'name' => 'event_logo',
                'type' => 'image',
                'save_format' => 'object',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array (
                'key' => 'field_595ee93d9b347',
                'label' => 'Organisation',
                'name' => 'organisation',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_595ee9619b349',
                'label' => 'Venue',
                'name' => 'venue',
                'type' => 'textarea',
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'formatting' => 'br',
            ),
            array (
                'key' => 'field_595eeb529b350',
                'label' => 'Speakers',
                'name' => 'speakers',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_595eeaff9b34d',
                'label' => 'Primary theme',
                'name' => 'primary_theme',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_595eeb099b34e',
                'label' => 'Sub theme',
                'name' => 'sub_theme',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_595eef3fe2d1b',
                'label' => 'Website',
                'name' => 'website',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => 'http://',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_595eebde9b356',
                'label' => 'Invite only',
                'name' => 'invite_only',
                'type' => 'true_false',
                'message' => 'Is the event invite only?',
                'default_value' => 0,
            ),
            array (
                'key' => 'field_595eec089b357',
                'label' => 'Registration',
                'name' => 'registration',
                'type' => 'true_false',
                'message' => 'Is registration required?',
                'default_value' => 0,
            ),
            array (
                'key' => 'field_595eebc79b355',
                'label' => 'Booking URL',
                'name' => 'booking_url',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'event',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'acf_after_title',
            'layout' => 'default',
            'hide_on_screen' => array (
                0 => 'permalink',
                1 => 'the_content',
                2 => 'excerpt',
                3 => 'custom_fields',
                4 => 'discussion',
                5 => 'comments',
                6 => 'revisions',
                7 => 'slug',
                8 => 'author',
                9 => 'format',
                10 => 'featured_image',
                11 => 'categories',
                12 => 'tags',
                13 => 'send-trackbacks',
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_event-images',
        'title' => 'Event Images',
        'fields' => array (
            array (
                'key' => 'field_595eedd9f600c',
                'label' => 'Event image',
                'name' => 'event_image',
                'type' => 'image',
                'save_format' => 'object',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'event',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'side',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 1,
    ));
}